#ifndef RESCAN_MACROS
#define RESCAN_MACROS

namespace ReScan
{
#define ZERO_CLAMP								0.001

#define SUCCESS_CODE							0

#define MEMORY_ALLOCATION_ERROR_CODE			1
#define FILE_NOT_FOUND_ERROR_CODE				2

#define INVALID_FILE_ERROR_CODE					100
#define INVALID_PLAN_ERROR_CODE					101
#define NO_PLAN_SELECTED_ERROR_CODE				102
#define NO_STEP_AXIS_1_SELECTED_ERROR_CODE		103
#define NO_STEP_AXIS_2_SELECTED_ERROR_CODE		104
#define NO_POINT_1_SELECTED_ERROR_CODE			105
#define NO_POINT_2_SELECTED_ERROR_CODE			106
#define NO_PLAN_OFFSET_SELECTED_ERROR_CODE		107
#define IDENTICAL_POINTS_HEIGHT					108

#define SAVE_CONFIG_ERROR_CODE					200
#define READ_CONFIG_ERROR_CODE					201
#define SET_CONFIG_ERROR_CODE					202
#define SAVE_CSV_ERROR_CODE						203
#define READ_CSV_ERROR_CODE						204

#define NO_MATRIX_INVERSE_ERROR_CODE			300
}

#endif // RESCAN_MACROS